In [ ]:
! pip install pymysql
! pip install sqlalchemy
import pandas as pd
from sqlalchemy import create_engine

Collecting pymysql
  Downloading PyMySQL-1.1.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 720.7 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.0
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.23)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.0.2)

In [ ]:
# Load your dataset into a Pandas DataFrame with the appropriate encoding
df = pd.read_csv('/content/ischemic-strokedata-ca-hospitals.csv', encoding='latin1')

In [ ]:
# Select only the desired columns
selected_columns = ['County', 'Hospital', 'Measure', 'Risk Adjusted Rate', '# of Deaths/Readmissions', '# of Cases', 'Hospital Ratings']
df = df[selected_columns]

In [ ]:
# Replace spaces with underscores in column names
df.columns = df.columns.str.replace(' ', '_')

# Drop rows with any NaN values
df = df.dropna()

# Drop rows with empty strings in all columns
df = df.replace(r'^\s*$', pd.NA, regex=True)
df = df.dropna()

# Drop rows with a specific value (e.g., "AAAA") in any column
df = df[~df.apply(lambda row: any(row == 'AAAA'), axis=1)]

# Reset index after dropping rows
df = df.reset_index(drop=True)

In [ ]:
# Create a new engine for reading and writing data
db_ip = '35.202.151.235'
db_port = '3306'
db_username = 'root'
db_password = 'tholvi98jm'
db_name = 'finalproject'
table_name = 'california_ischemic_stroke_data'

In [ ]:
engine = create_engine(f'mysql+pymysql://{db_username}:{db_password}@{db_ip}:{db_port}/{db_name}')

In [ ]:
# Write the DataFrame to MySQL
df.to_sql(name=table_name, con=engine, index=False, if_exists='replace')

2170